### ISSUE TITLE
Blog post to BIOS2 website

### ISSUE THREAD

**Issue by graciellehigino** [PoisotLab/data-trek-2020#2]
Hey, folks!

There's a draft of the blog post [here](https://github.com/PoisotLab/data-trek-2020/blob/data-wrangling/blog/blog_post.md). Could you all take a look, comment, edit, etc? Thanks!!

Too afraid to PR this.

**Comment by gabrieldansereau** [comment]
Archiving this repo and moving further development to the [Randonnees-Datatrek fork](https://github.com/Randonnees-Datatrek/data-trek-2020).
